name: PR Backend

on:
  pull_request:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v5
        
      - name: 🐻 Setup Golang
        uses: actions/setup-go@v6
        with:
          go-version: '1.24'
          cache: false

      - name: 🔍 Lint code
        uses: golangci/golangci-lint-action@v9
        with:
          working-directory: backend
          args: --timeout=5m

      - name: 📁 Install test dependencies
        run: |
          go install gotest.tools/gotestsum@latest

      - name: 🧪 Run tests
        working-directory: backend
        run: | 
          make test
