name: PR Frontend

on:
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v6

      - name: 📦 Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: 📁 Install dependencies
        working-directory: frontend
        run: |
          npm ci

      - name: 🔍 Lint code
        working-directory: frontend
        run: |
          npx prettier --check src e2e && npx eslint src --max-warnings 0

      - name: 🧪 Run tests 
        working-directory: frontend
        run: |
          npx playwright install
          npm run test

      - name: 🛠 Build application
        working-directory: frontend
        run: |
          npm run build

      - name: 🔎 Svelte Check
        working-directory: frontend
        run: |
          npx svelte-kit sync && npx svelte-check --tsconfig ./tsconfig.json --fail-on-warnings
